name: Release

on:
  push:
  workflow_dispatch:
    inputs:
      forceBuild:
        description: "Force image build"
        required: false
        default: false
        type: boolean

env:
  BUILD_IMAGE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.forceBuild == 'true' }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      buildImage: ${{ steps.check.outputs.buildImage }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run check and reset
        id: check
        run: |
          echo ::set-output name=buildImage::true

  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.buildImage == 'true' }}
    steps:
      - name: Do It
        run: |
          echo ${{ needs.setup.outputs.buildImage }}
